### ISSUE TITLE
display issue with the phenotype table

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/civic-v2#1060] opened 2024-05-18 17:51 UTC
The evidence and assertion count values do not align with the column header boundaries in the phenotype table:

![image](https://github.com/griffithlab/civic-v2/assets/811065/46646aad-c54b-4b67-933b-28d4ca473c14)

**Comment by susannasiebert** [comment] 2024-05-20 14:03
Which browser are you using? I'm unable to replicate this on Chrome Version 124.0.6367.119. The space on the right is where the vertical scroll bar should be. This appears to be missing in your screenshot so the table values align to fill the space. Does the scrollbar appear for you in other tables?

**Comment by susannasiebert** [comment] 2024-05-20 15:26
After chatting with @jmcmichael this might be a side effect of having scrollbars always turned on in your browser setting. Josh isn't able to replicate this issue in his browser, where his scrollbar settings are "Automatically based on mouse or trackpad".

**Comment by jmcmichael** [comment] 2024-05-20 15:52
In macOS, one may toggle scrollbar options in System Settings / Appearance / Show scroll bars.

**Comment by susannasiebert** [comment] 2024-05-22 13:37
Since this is not a bug, per se, but a limitation of the ng-zorro component library we are using in combination with a specific user system setting, there isn't really anything we can do on our end to address this short of using a different component library. Closing this issue as "wontfix".

**Closed by susannasiebert** 2024-05-22 13:37 UTC
Labels: wontfix

**Comment by jmcmichael** [comment] 2024-05-22 16:18
I believe [this open issue](https://github.com/NG-ZORRO/ng-zorro-antd/issues/8470) is what we are seeing.
