### ISSUE TITLE
After making new evidence item screen dissapears

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-v2#351] opened 2022-04-01 15:13 UTC
<img width="1440" alt="blankscreen" src="https://user-images.githubusercontent.com/13948978/161291780-94e6a162-fdce-4e8f-bf3b-6f0822fb5fc3.png">

After making a new Evidence Item, there was a notification that said I could view the submitted evidence item details. When clicking that, it took me to a blank screen. 

Using Chrome on OS Catalina

**Comment by kkrysiak** [comment] 2022-04-01 15:17
Duplicate of https://github.com/griffithlab/civic-v2/issues/330

**Closed** 2022-04-01 15:21 UTC
