### ISSUE TITLE
Add evidence form says it is submitting a revision

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#343] opened 2022-04-01 14:22 UTC
Add Evidence is both requiring a comment (which we don't want) and claiming I am submitting a revision.
<img width="1007" alt="Screen Shot 2022-04-01 at 9 21 34 AM" src="https://user-images.githubusercontent.com/8527125/161282660-c3bfd320-ecca-443e-9492-44acf2cc885e.png">

**Comment by kkrysiak** [comment] 2022-04-01 14:23
EID8958

**Comment by acoffman** [comment] 2022-04-01 15:18
The first two items are resolved in #329. I cannot reproduce the assertion submission error; do you recall anything about the assertion you were trying to add?

**Closed** 2022-04-05 19:41 UTC
