### ISSUE TITLE
display gene & variant lists in variant groups table as tags

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-v2#412] opened 2022-04-08 19:20 UTC
Currently, genes and variants are displayed in the variant group table as comma-delimited strings, it would be cool to display them as gene and variant tags to show detail popovers and provide links to the listed entities. Needs some API work as these lists are provided to the client as string arrays.

**Comment by susannasiebert** [comment] 2022-04-11 14:22
This is a duplicate of #272

**Closed by susannasiebert** 2022-04-11 14:22 UTC
