### ISSUE TITLE
revision notification does not go away after accepting unless you hard refresh

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-v2#463] opened 2022-04-14 19:51 UTC
![Screen Shot 2022-04-14 at 2 48 47 PM](https://user-images.githubusercontent.com/856728/163465365-fa45b32c-f3c2-4a91-bbf8-17dbc66967d5.png)

After accepting a revision I have to do a hard refresh to get the red notification like in this screenshot to update

**Comment by susannasiebert** [comment] 2022-04-15 13:50
This is a duplicate of #462.

**Closed by susannasiebert** 2022-04-15 13:50 UTC
